"""Add Reporting Models

Revision ID: 34cc58beac00
Revises: 98af5f1e3d81
Create Date: 2026-06-17 09:55:50.225113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34cc58beac00"
down_revision: Union[str, Sequence[str], None] = "98af5f1e3d81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_snapshots",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("metrics_json", sa.Text(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dashboard_snapshots_project_id"),
        "dashboard_snapshots",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_reports",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("report_type", sa.String(length=50), nullable=False),
        sa.Column("frequency", sa.String(length=50), nullable=False),
        sa.Column("last_run", sa.DateTime(), nullable=True),
        sa.Column("next_run", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_reports_project_id"),
        "scheduled_reports",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_scheduled_reports_project_id"), table_name="scheduled_reports"
    )
    op.drop_table("scheduled_reports")
    op.drop_index(
        op.f("ix_dashboard_snapshots_project_id"), table_name="dashboard_snapshots"
    )
    op.drop_table("dashboard_snapshots")
    # ### end Alembic commands ###
