"""Add Intelligence Models

Revision ID: 98af5f1e3d81
Revises: b0d46eca5b95
Create Date: 2026-06-17 09:52:22.796876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98af5f1e3d81"
down_revision: Union[str, Sequence[str], None] = "b0d46eca5b95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_history",
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("event", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_history_asset_id"), "asset_history", ["asset_id"], unique=False
    )
    op.create_table(
        "asset_relationships",
        sa.Column("parent_asset_id", sa.String(), nullable=False),
        sa.Column("child_asset_id", sa.String(), nullable=False),
        sa.Column("relationship_type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_relationships_child_asset_id"),
        "asset_relationships",
        ["child_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_relationships_parent_asset_id"),
        "asset_relationships",
        ["parent_asset_id"],
        unique=False,
    )
    op.create_table(
        "asset_tags",
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("tag", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_tags_asset_id"), "asset_tags", ["asset_id"], unique=False
    )
    op.create_index(op.f("ix_asset_tags_tag"), "asset_tags", ["tag"], unique=False)
    op.create_table(
        "intelligence_records",
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_intelligence_records_asset_id"),
        "intelligence_records",
        ["asset_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_intelligence_records_asset_id"), table_name="intelligence_records"
    )
    op.drop_table("intelligence_records")
    op.drop_index(op.f("ix_asset_tags_tag"), table_name="asset_tags")
    op.drop_index(op.f("ix_asset_tags_asset_id"), table_name="asset_tags")
    op.drop_table("asset_tags")
    op.drop_index(
        op.f("ix_asset_relationships_parent_asset_id"), table_name="asset_relationships"
    )
    op.drop_index(
        op.f("ix_asset_relationships_child_asset_id"), table_name="asset_relationships"
    )
    op.drop_table("asset_relationships")
    op.drop_index(op.f("ix_asset_history_asset_id"), table_name="asset_history")
    op.drop_table("asset_history")
    # ### end Alembic commands ###
