"""Add WorkflowExecution

Revision ID: b0d46eca5b95
Revises: 4a23656c4b32
Create Date: 2026-06-17 09:47:53.609280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0d46eca5b95"
down_revision: Union[str, Sequence[str], None] = "4a23656c4b32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_executions",
        sa.Column("workflow_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("target", sa.String(length=255), nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_executions_target"),
        "workflow_executions",
        ["target"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_executions_workflow_name"),
        "workflow_executions",
        ["workflow_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_executions_workflow_name"), table_name="workflow_executions"
    )
    op.drop_index(
        op.f("ix_workflow_executions_target"), table_name="workflow_executions"
    )
    op.drop_table("workflow_executions")
    # ### end Alembic commands ###
