name: bug_bounty
stages:
  - subfinder
  - amass
  - httpx:
      depends_on:
        - subfinder
        - amass
  - katana:
      depends_on:
        - httpx
  - nuclei:
      depends_on:
        - httpx
