// Code generated by 'yaegi extract github.com/Autumn-27/ScopeSentry/internal/utils/ct/models'. DO NOT EDIT.

package symbols

import (
	"github.com/Autumn-27/ScopeSentry/internal/utils/ct/models"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/Autumn-27/ScopeSentry/internal/utils/ct/models/models"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"EventTypeCertificateProcessed": reflect.ValueOf(models.EventTypeCertificateProcessed),
		"EventTypeErrorOccurred":        reflect.ValueOf(models.EventTypeErrorOccurred),
		"EventTypeSDKStarted":           reflect.ValueOf(models.EventTypeSDKStarted),
		"EventTypeSDKStopped":           reflect.ValueOf(models.EventTypeSDKStopped),
		"EventTypeSubdomainDiscovered":  reflect.ValueOf(models.EventTypeSubdomainDiscovered),
		"EventTypeWatcherStatusChanged": reflect.ValueOf(models.EventTypeWatcherStatusChanged),
		"GenerateEventID":               reflect.ValueOf(models.GenerateEventID),
		"NewCheckpoint":                 reflect.ValueOf(models.NewCheckpoint),
		"NewDomain":                     reflect.ValueOf(models.NewDomain),
		"NewDomainMatch":                reflect.ValueOf(models.NewDomainMatch),
		"NewDomainTrieNode":             reflect.ValueOf(models.NewDomainTrieNode),
		"NewEventBus":                   reflect.ValueOf(models.NewEventBus),
		"NewSDKStatus":                  reflect.ValueOf(models.NewSDKStatus),
		"NewWatcherStatus":              reflect.ValueOf(models.NewWatcherStatus),
		"NormalizeDomain":               reflect.ValueOf(models.NormalizeDomain),
		"ValidateDomain":                reflect.ValueOf(models.ValidateDomain),

		// type definitions
		"BaseEvent":                 reflect.ValueOf((*models.BaseEvent)(nil)),
		"BloomFilterStats":          reflect.ValueOf((*models.BloomFilterStats)(nil)),
		"CacheStats":                reflect.ValueOf((*models.CacheStats)(nil)),
		"CertInfo":                  reflect.ValueOf((*models.CertInfo)(nil)),
		"CertificateCallback":       reflect.ValueOf((*models.CertificateCallback)(nil)),
		"CertificateProcessedEvent": reflect.ValueOf((*models.CertificateProcessedEvent)(nil)),
		"Checkpoint":                reflect.ValueOf((*models.Checkpoint)(nil)),
		"CheckpointManager":         reflect.ValueOf((*models.CheckpointManager)(nil)),
		"Domain":                    reflect.ValueOf((*models.Domain)(nil)),
		"DomainMatch":               reflect.ValueOf((*models.DomainMatch)(nil)),
		"DomainMatcherInterface":    reflect.ValueOf((*models.DomainMatcherInterface)(nil)),
		"DomainMatcherStats":        reflect.ValueOf((*models.DomainMatcherStats)(nil)),
		"DomainStats":               reflect.ValueOf((*models.DomainStats)(nil)),
		"DomainTrieNode":            reflect.ValueOf((*models.DomainTrieNode)(nil)),
		"ErrorCallback":             reflect.ValueOf((*models.ErrorCallback)(nil)),
		"ErrorOccurredEvent":        reflect.ValueOf((*models.ErrorOccurredEvent)(nil)),
		"Event":                     reflect.ValueOf((*models.Event)(nil)),
		"EventBus":                  reflect.ValueOf((*models.EventBus)(nil)),
		"EventHandler":              reflect.ValueOf((*models.EventHandler)(nil)),
		"EventType":                 reflect.ValueOf((*models.EventType)(nil)),
		"GCStats":                   reflect.ValueOf((*models.GCStats)(nil)),
		"LogServerConfig":           reflect.ValueOf((*models.LogServerConfig)(nil)),
		"LogStatus":                 reflect.ValueOf((*models.LogStatus)(nil)),
		"ProcessingStats":           reflect.ValueOf((*models.ProcessingStats)(nil)),
		"SDKLifecycleEvent":         reflect.ValueOf((*models.SDKLifecycleEvent)(nil)),
		"SDKStats":                  reflect.ValueOf((*models.SDKStats)(nil)),
		"SDKStatus":                 reflect.ValueOf((*models.SDKStatus)(nil)),
		"StatusCallback":            reflect.ValueOf((*models.StatusCallback)(nil)),
		"SubdomainCallback":         reflect.ValueOf((*models.SubdomainCallback)(nil)),
		"SubdomainDiscoveredEvent":  reflect.ValueOf((*models.SubdomainDiscoveredEvent)(nil)),
		"SubdomainEvent":            reflect.ValueOf((*models.SubdomainEvent)(nil)),
		"TrieStats":                 reflect.ValueOf((*models.TrieStats)(nil)),
		"WatcherStatus":             reflect.ValueOf((*models.WatcherStatus)(nil)),
		"WatcherStatusChangedEvent": reflect.ValueOf((*models.WatcherStatusChangedEvent)(nil)),

		// interface wrapper definitions
		"_CheckpointManager":      reflect.ValueOf((*_github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_CheckpointManager)(nil)),
		"_DomainMatcherInterface": reflect.ValueOf((*_github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface)(nil)),
		"_Event":                  reflect.ValueOf((*_github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_Event)(nil)),
		"_EventHandler":           reflect.ValueOf((*_github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_EventHandler)(nil)),
	}
}

// _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_CheckpointManager is an interface wrapper for CheckpointManager type
type _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_CheckpointManager struct {
	IValue            interface{}
	WCleanupExpired   func(olderThan time.Duration) error
	WDeleteCheckpoint func(url string) error
	WListCheckpoints  func() ([]*models.Checkpoint, error)
	WLoadCheckpoint   func(url string) (*models.Checkpoint, error)
	WSaveCheckpoint   func(cp *models.Checkpoint) error
}

func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_CheckpointManager) CleanupExpired(olderThan time.Duration) error {
	return W.WCleanupExpired(olderThan)
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_CheckpointManager) DeleteCheckpoint(url string) error {
	return W.WDeleteCheckpoint(url)
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_CheckpointManager) ListCheckpoints() ([]*models.Checkpoint, error) {
	return W.WListCheckpoints()
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_CheckpointManager) LoadCheckpoint(url string) (*models.Checkpoint, error) {
	return W.WLoadCheckpoint(url)
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_CheckpointManager) SaveCheckpoint(cp *models.Checkpoint) error {
	return W.WSaveCheckpoint(cp)
}

// _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface is an interface wrapper for DomainMatcherInterface type
type _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface struct {
	IValue           interface{}
	WAddDomain       func(domain string) error
	WClear           func() error
	WGetAllDomains   func() []string
	WGetStats        func() *models.DomainMatcherStats
	WHasDomain       func(domain string) bool
	WIsSubdomainOf   func(subdomain string, rootDomain string) bool
	WMatchSubdomains func(domains []string) []*models.DomainMatch
	WRemoveDomain    func(domain string) error
}

func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface) AddDomain(domain string) error {
	return W.WAddDomain(domain)
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface) Clear() error {
	return W.WClear()
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface) GetAllDomains() []string {
	return W.WGetAllDomains()
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface) GetStats() *models.DomainMatcherStats {
	return W.WGetStats()
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface) HasDomain(domain string) bool {
	return W.WHasDomain(domain)
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface) IsSubdomainOf(subdomain string, rootDomain string) bool {
	return W.WIsSubdomainOf(subdomain, rootDomain)
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface) MatchSubdomains(domains []string) []*models.DomainMatch {
	return W.WMatchSubdomains(domains)
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_DomainMatcherInterface) RemoveDomain(domain string) error {
	return W.WRemoveDomain(domain)
}

// _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_Event is an interface wrapper for Event type
type _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_Event struct {
	IValue        interface{}
	WGetID        func() string
	WGetTimestamp func() time.Time
	WGetType      func() models.EventType
}

func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_Event) GetID() string {
	return W.WGetID()
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_Event) GetTimestamp() time.Time {
	return W.WGetTimestamp()
}
func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_Event) GetType() models.EventType {
	return W.WGetType()
}

// _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_EventHandler is an interface wrapper for EventHandler type
type _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_EventHandler struct {
	IValue       interface{}
	WHandleEvent func(event models.Event) error
}

func (W _github_com_Autumn_27_ScopeSentry_internal_utils_ct_models_EventHandler) HandleEvent(event models.Event) error {
	return W.WHandleEvent(event)
}
