// Code generated by 'yaegi extract github.com/Autumn-27/ScopeSentry/internal/utils'. DO NOT EDIT.

package symbols

import (
	"github.com/Autumn-27/ScopeSentry/internal/utils"
	"reflect"
)

func init() {
	Symbols["github.com/Autumn-27/ScopeSentry/internal/utils/utils"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CancelContext": reflect.ValueOf(utils.CancelContext),
		"DeleteFile":    reflect.ValueOf(utils.DeleteFile),
		"DownloadFile":  reflect.ValueOf(utils.DownloadFile),
		"EnsureDir":     reflect.ValueOf(utils.EnsureDir),
		"GetContext":    reflect.ValueOf(utils.GetContext),
		"HasContext":    reflect.ValueOf(utils.HasContext),
		"HttpClient":    reflect.ValueOf(&utils.HttpClient).Elem(),
		"Marshal":       reflect.ValueOf(utils.Marshal),
		"Requests":      reflect.ValueOf(&utils.Requests).Elem(),
		"Unmarshal":     reflect.ValueOf(utils.Unmarshal),
		"WriteFile":     reflect.ValueOf(utils.WriteFile),

		// type definitions
		"GetHttpResponse": reflect.ValueOf((*utils.GetHttpResponse)(nil)),
		"HttpResponse":    reflect.ValueOf((*utils.HttpResponse)(nil)),
	}
}
