// Code generated by 'yaegi extract github.com/Autumn-27/ScopeSentry/internal/utils/ct'. DO NOT EDIT.

package symbols

import (
	"github.com/Autumn-27/ScopeSentry/internal/utils/ct"
	"reflect"
)

func init() {
	Symbols["github.com/Autumn-27/ScopeSentry/internal/utils/ct/ct"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewAutoCheckpointSaver":    reflect.ValueOf(ct.NewAutoCheckpointSaver),
		"NewBloomFilter":            reflect.ValueOf(ct.NewBloomFilter),
		"NewCTWatcher":              reflect.ValueOf(ct.NewCTWatcher),
		"NewCTWatcherSDK":           reflect.ValueOf(ct.NewCTWatcherSDK),
		"NewCertificateParser":      reflect.ValueOf(ct.NewCertificateParser),
		"NewDomainMatcher":          reflect.ValueOf(ct.NewDomainMatcher),
		"NewLRUCache":               reflect.ValueOf(ct.NewLRUCache),
		"NewRedisCheckpointManager": reflect.ValueOf(ct.NewRedisCheckpointManager),
		"NewStreamProcessor":        reflect.ValueOf(ct.NewStreamProcessor),

		// type definitions
		"AutoCheckpointSaver":     reflect.ValueOf((*ct.AutoCheckpointSaver)(nil)),
		"BloomFilter":             reflect.ValueOf((*ct.BloomFilter)(nil)),
		"CTWatcher":               reflect.ValueOf((*ct.CTWatcher)(nil)),
		"CTWatcherSDK":            reflect.ValueOf((*ct.CTWatcherSDK)(nil)),
		"CertificateEventHandler": reflect.ValueOf((*ct.CertificateEventHandler)(nil)),
		"CertificateParser":       reflect.ValueOf((*ct.CertificateParser)(nil)),
		"CheckpointStats":         reflect.ValueOf((*ct.CheckpointStats)(nil)),
		"DomainMatcher":           reflect.ValueOf((*ct.DomainMatcher)(nil)),
		"ErrorEventHandler":       reflect.ValueOf((*ct.ErrorEventHandler)(nil)),
		"LRUCache":                reflect.ValueOf((*ct.LRUCache)(nil)),
		"ParserStats":             reflect.ValueOf((*ct.ParserStats)(nil)),
		"RedisCheckpointManager":  reflect.ValueOf((*ct.RedisCheckpointManager)(nil)),
		"StreamProcessor":         reflect.ValueOf((*ct.StreamProcessor)(nil)),
		"StreamProcessorStats":    reflect.ValueOf((*ct.StreamProcessorStats)(nil)),
		"SubdomainEventHandler":   reflect.ValueOf((*ct.SubdomainEventHandler)(nil)),
		"WatcherStats":            reflect.ValueOf((*ct.WatcherStats)(nil)),
	}
}
