// Code generated by 'yaegi extract github.com/Autumn-27/ScopeSentry/internal/options'. DO NOT EDIT.

package symbols

import (
	"github.com/Autumn-27/ScopeSentry/internal/options"
	"reflect"
)

func init() {
	Symbols["github.com/Autumn-27/ScopeSentry/internal/options/options"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewOption":        reflect.ValueOf(options.NewOption),
		"PluginOptionInit": reflect.ValueOf(&options.PluginOptionInit).Elem(),

		// type definitions
		"PluginOption": reflect.ValueOf((*options.PluginOption)(nil)),
	}
}
