// Code generated by 'yaegi extract github.com/Autumn-27/ScopeSentry/internal/utils/helper'. DO NOT EDIT.

package symbols

import (
	"github.com/Autumn-27/ScopeSentry/internal/utils/helper"
	"reflect"
)

func init() {
	Symbols["github.com/Autumn-27/ScopeSentry/internal/utils/helper/helper"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CalculateMD5FromContent":    reflect.ValueOf(helper.CalculateMD5FromContent),
		"ConvertFofaToCustomQuery":   reflect.ValueOf(helper.ConvertFofaToCustomQuery),
		"ConvertShodanToCustomQuery": reflect.ValueOf(helper.ConvertShodanToCustomQuery),
		"FormatTime":                 reflect.ValueOf(helper.FormatTime),
		"GenerateIPRange":            reflect.ValueOf(helper.GenerateIPRange),
		"GenerateIgnore":             reflect.ValueOf(helper.GenerateIgnore),
		"GenerateTarget":             reflect.ValueOf(helper.GenerateTarget),
		"GetNowTime":                 reflect.ValueOf(helper.GetNowTime),
		"GetNowTimeString":           reflect.ValueOf(helper.GetNowTimeString),
		"GetRootDomain":              reflect.ValueOf(helper.GetRootDomain),
		"GetSearchQuery":             reflect.ValueOf(helper.GetSearchQuery),
		"GetTargetList":              reflect.ValueOf(helper.GetTargetList),
		"HashXX64String":             reflect.ValueOf(helper.HashXX64String),
		"NewCache":                   reflect.ValueOf(helper.NewCache),
		"NextIP":                     reflect.ValueOf(helper.NextIP),
		"RemoveArrayDuplicates":      reflect.ValueOf(helper.RemoveArrayDuplicates),
		"SafeParseURL":               reflect.ValueOf(helper.SafeParseURL),
		"SearchKey":                  reflect.ValueOf(&helper.SearchKey).Elem(),
		"SearchToMongoDB":            reflect.ValueOf(helper.SearchToMongoDB),
		"Sha256Hex":                  reflect.ValueOf(helper.Sha256Hex),
		"StringInSlice":              reflect.ValueOf(helper.StringInSlice),
		"StringToPostfix":            reflect.ValueOf(helper.StringToPostfix),

		// type definitions
		"Cache": reflect.ValueOf((*helper.Cache)(nil)),
	}
}
