// Code generated by 'yaegi extract github.com/Autumn-27/ScopeSentry/internal/utils/random'. DO NOT EDIT.

package symbols

import (
	"github.com/Autumn-27/ScopeSentry/internal/utils/random"
	"reflect"
)

func init() {
	Symbols["github.com/Autumn-27/ScopeSentry/internal/utils/random/random"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GeneratePassword":     reflect.ValueOf(random.GeneratePassword),
		"GeneratePluginKey":    reflect.ValueOf(random.GeneratePluginKey),
		"GenerateRandomString": reflect.ValueOf(random.GenerateRandomString),
		"GenerateSecretKey":    reflect.ValueOf(random.GenerateSecretKey),
		"GenerateString":       reflect.ValueOf(random.GenerateString),
	}
}
