// Code generated by 'yaegi extract github.com/Autumn-27/ScopeSentry/internal/utils/ct/types'. DO NOT EDIT.

package symbols

import (
	"github.com/Autumn-27/ScopeSentry/internal/utils/ct/types"
	"reflect"
)

func init() {
	Symbols["github.com/Autumn-27/ScopeSentry/internal/utils/ct/types/types"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultSDKOptions": reflect.ValueOf(types.DefaultSDKOptions),

		// type definitions
		"DomainMatcherConfig": reflect.ValueOf((*types.DomainMatcherConfig)(nil)),
		"LogServerConfig":     reflect.ValueOf((*types.LogServerConfig)(nil)),
		"PerformanceConfig":   reflect.ValueOf((*types.PerformanceConfig)(nil)),
		"RedisConfig":         reflect.ValueOf((*types.RedisConfig)(nil)),
		"SDKOptions":          reflect.ValueOf((*types.SDKOptions)(nil)),
		"Status":              reflect.ValueOf((*types.Status)(nil)),
		"ValidationError":     reflect.ValueOf((*types.ValidationError)(nil)),
	}
}
