// Code generated by 'yaegi extract go.mongodb.org/mongo-driver/bson/primitive'. DO NOT EDIT.

package symbols

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["go.mongodb.org/mongo-driver/bson/primitive/primitive"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CompareTimestamp":          reflect.ValueOf(primitive.CompareTimestamp),
		"ErrInvalidHex":             reflect.ValueOf(&primitive.ErrInvalidHex).Elem(),
		"ErrParseInf":               reflect.ValueOf(&primitive.ErrParseInf).Elem(),
		"ErrParseNaN":               reflect.ValueOf(&primitive.ErrParseNaN).Elem(),
		"ErrParseNegInf":            reflect.ValueOf(&primitive.ErrParseNegInf).Elem(),
		"IsValidObjectID":           reflect.ValueOf(primitive.IsValidObjectID),
		"MaxDecimal128Exp":          reflect.ValueOf(constant.MakeFromLiteral("6111", token.INT, 0)),
		"MinDecimal128Exp":          reflect.ValueOf(constant.MakeFromLiteral("-6176", token.INT, 0)),
		"NewDateTimeFromTime":       reflect.ValueOf(primitive.NewDateTimeFromTime),
		"NewDecimal128":             reflect.ValueOf(primitive.NewDecimal128),
		"NewObjectID":               reflect.ValueOf(primitive.NewObjectID),
		"NewObjectIDFromTimestamp":  reflect.ValueOf(primitive.NewObjectIDFromTimestamp),
		"NilObjectID":               reflect.ValueOf(&primitive.NilObjectID).Elem(),
		"ObjectIDFromHex":           reflect.ValueOf(primitive.ObjectIDFromHex),
		"ParseDecimal128":           reflect.ValueOf(primitive.ParseDecimal128),
		"ParseDecimal128FromBigInt": reflect.ValueOf(primitive.ParseDecimal128FromBigInt),

		// type definitions
		"A":             reflect.ValueOf((*primitive.A)(nil)),
		"Binary":        reflect.ValueOf((*primitive.Binary)(nil)),
		"CodeWithScope": reflect.ValueOf((*primitive.CodeWithScope)(nil)),
		"D":             reflect.ValueOf((*primitive.D)(nil)),
		"DBPointer":     reflect.ValueOf((*primitive.DBPointer)(nil)),
		"DateTime":      reflect.ValueOf((*primitive.DateTime)(nil)),
		"Decimal128":    reflect.ValueOf((*primitive.Decimal128)(nil)),
		"E":             reflect.ValueOf((*primitive.E)(nil)),
		"JavaScript":    reflect.ValueOf((*primitive.JavaScript)(nil)),
		"M":             reflect.ValueOf((*primitive.M)(nil)),
		"MaxKey":        reflect.ValueOf((*primitive.MaxKey)(nil)),
		"MinKey":        reflect.ValueOf((*primitive.MinKey)(nil)),
		"Null":          reflect.ValueOf((*primitive.Null)(nil)),
		"ObjectID":      reflect.ValueOf((*primitive.ObjectID)(nil)),
		"Regex":         reflect.ValueOf((*primitive.Regex)(nil)),
		"Symbol":        reflect.ValueOf((*primitive.Symbol)(nil)),
		"Timestamp":     reflect.ValueOf((*primitive.Timestamp)(nil)),
		"Undefined":     reflect.ValueOf((*primitive.Undefined)(nil)),
	}
}
