// Code generated by 'yaegi extract go.mongodb.org/mongo-driver/mongo/options'. DO NOT EDIT.

package symbols

import (
	"context"
	"go.mongodb.org/mongo-driver/mongo/options"
	"go/constant"
	"go/token"
	"net"
	"reflect"
)

func init() {
	Symbols["go.mongodb.org/mongo-driver/mongo/options/options"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"After":                              reflect.ValueOf(options.After),
		"Aggregate":                          reflect.ValueOf(options.Aggregate),
		"AutoEncryption":                     reflect.ValueOf(options.AutoEncryption),
		"Before":                             reflect.ValueOf(options.Before),
		"BuildTLSConfig":                     reflect.ValueOf(options.BuildTLSConfig),
		"BulkWrite":                          reflect.ValueOf(options.BulkWrite),
		"ChangeStream":                       reflect.ValueOf(options.ChangeStream),
		"Client":                             reflect.ValueOf(options.Client),
		"ClientEncryption":                   reflect.ValueOf(options.ClientEncryption),
		"Collection":                         reflect.ValueOf(options.Collection),
		"Count":                              reflect.ValueOf(options.Count),
		"CreateCollection":                   reflect.ValueOf(options.CreateCollection),
		"CreateIndexes":                      reflect.ValueOf(options.CreateIndexes),
		"CreateView":                         reflect.ValueOf(options.CreateView),
		"DataKey":                            reflect.ValueOf(options.DataKey),
		"Database":                           reflect.ValueOf(options.Database),
		"Default":                            reflect.ValueOf(options.Default),
		"DefaultCausalConsistency":           reflect.ValueOf(&options.DefaultCausalConsistency).Elem(),
		"DefaultChunkSize":                   reflect.ValueOf(&options.DefaultChunkSize).Elem(),
		"DefaultIndex":                       reflect.ValueOf(options.DefaultIndex),
		"DefaultName":                        reflect.ValueOf(&options.DefaultName).Elem(),
		"DefaultOrdered":                     reflect.ValueOf(&options.DefaultOrdered).Elem(),
		"DefaultRevision":                    reflect.ValueOf(&options.DefaultRevision).Elem(),
		"Delete":                             reflect.ValueOf(options.Delete),
		"Distinct":                           reflect.ValueOf(options.Distinct),
		"DropIndexes":                        reflect.ValueOf(options.DropIndexes),
		"Encrypt":                            reflect.ValueOf(options.Encrypt),
		"EstimatedDocumentCount":             reflect.ValueOf(options.EstimatedDocumentCount),
		"Find":                               reflect.ValueOf(options.Find),
		"FindOne":                            reflect.ValueOf(options.FindOne),
		"FindOneAndDelete":                   reflect.ValueOf(options.FindOneAndDelete),
		"FindOneAndReplace":                  reflect.ValueOf(options.FindOneAndReplace),
		"FindOneAndUpdate":                   reflect.ValueOf(options.FindOneAndUpdate),
		"GridFSBucket":                       reflect.ValueOf(options.GridFSBucket),
		"GridFSFind":                         reflect.ValueOf(options.GridFSFind),
		"GridFSName":                         reflect.ValueOf(options.GridFSName),
		"GridFSUpload":                       reflect.ValueOf(options.GridFSUpload),
		"Index":                              reflect.ValueOf(options.Index),
		"InsertMany":                         reflect.ValueOf(options.InsertMany),
		"InsertOne":                          reflect.ValueOf(options.InsertOne),
		"ListCollections":                    reflect.ValueOf(options.ListCollections),
		"ListDatabases":                      reflect.ValueOf(options.ListDatabases),
		"ListIndexes":                        reflect.ValueOf(options.ListIndexes),
		"LogComponentAll":                    reflect.ValueOf(options.LogComponentAll),
		"LogComponentCommand":                reflect.ValueOf(options.LogComponentCommand),
		"LogComponentConnection":             reflect.ValueOf(options.LogComponentConnection),
		"LogComponentServerSelection":        reflect.ValueOf(options.LogComponentServerSelection),
		"LogComponentTopology":               reflect.ValueOf(options.LogComponentTopology),
		"LogLevelDebug":                      reflect.ValueOf(options.LogLevelDebug),
		"LogLevelInfo":                       reflect.ValueOf(options.LogLevelInfo),
		"Logger":                             reflect.ValueOf(options.Logger),
		"MergeAggregateOptions":              reflect.ValueOf(options.MergeAggregateOptions),
		"MergeAutoEncryptionOptions":         reflect.ValueOf(options.MergeAutoEncryptionOptions),
		"MergeBucketOptions":                 reflect.ValueOf(options.MergeBucketOptions),
		"MergeBulkWriteOptions":              reflect.ValueOf(options.MergeBulkWriteOptions),
		"MergeChangeStreamOptions":           reflect.ValueOf(options.MergeChangeStreamOptions),
		"MergeClientEncryptionOptions":       reflect.ValueOf(options.MergeClientEncryptionOptions),
		"MergeClientOptions":                 reflect.ValueOf(options.MergeClientOptions),
		"MergeCollectionOptions":             reflect.ValueOf(options.MergeCollectionOptions),
		"MergeCountOptions":                  reflect.ValueOf(options.MergeCountOptions),
		"MergeCreateCollectionOptions":       reflect.ValueOf(options.MergeCreateCollectionOptions),
		"MergeCreateIndexesOptions":          reflect.ValueOf(options.MergeCreateIndexesOptions),
		"MergeCreateViewOptions":             reflect.ValueOf(options.MergeCreateViewOptions),
		"MergeDataKeyOptions":                reflect.ValueOf(options.MergeDataKeyOptions),
		"MergeDatabaseOptions":               reflect.ValueOf(options.MergeDatabaseOptions),
		"MergeDeleteOptions":                 reflect.ValueOf(options.MergeDeleteOptions),
		"MergeDistinctOptions":               reflect.ValueOf(options.MergeDistinctOptions),
		"MergeDropIndexesOptions":            reflect.ValueOf(options.MergeDropIndexesOptions),
		"MergeEncryptOptions":                reflect.ValueOf(options.MergeEncryptOptions),
		"MergeEstimatedDocumentCountOptions": reflect.ValueOf(options.MergeEstimatedDocumentCountOptions),
		"MergeFindOneAndDeleteOptions":       reflect.ValueOf(options.MergeFindOneAndDeleteOptions),
		"MergeFindOneAndReplaceOptions":      reflect.ValueOf(options.MergeFindOneAndReplaceOptions),
		"MergeFindOneAndUpdateOptions":       reflect.ValueOf(options.MergeFindOneAndUpdateOptions),
		"MergeFindOneOptions":                reflect.ValueOf(options.MergeFindOneOptions),
		"MergeFindOptions":                   reflect.ValueOf(options.MergeFindOptions),
		"MergeGridFSFindOptions":             reflect.ValueOf(options.MergeGridFSFindOptions),
		"MergeIndexOptions":                  reflect.ValueOf(options.MergeIndexOptions),
		"MergeInsertManyOptions":             reflect.ValueOf(options.MergeInsertManyOptions),
		"MergeInsertOneOptions":              reflect.ValueOf(options.MergeInsertOneOptions),
		"MergeListCollectionsOptions":        reflect.ValueOf(options.MergeListCollectionsOptions),
		"MergeListDatabasesOptions":          reflect.ValueOf(options.MergeListDatabasesOptions),
		"MergeListIndexesOptions":            reflect.ValueOf(options.MergeListIndexesOptions),
		"MergeNameOptions":                   reflect.ValueOf(options.MergeNameOptions),
		"MergeReplaceOptions":                reflect.ValueOf(options.MergeReplaceOptions),
		"MergeRewrapManyDataKeyOptions":      reflect.ValueOf(options.MergeRewrapManyDataKeyOptions),
		"MergeRunCmdOptions":                 reflect.ValueOf(options.MergeRunCmdOptions),
		"MergeSessionOptions":                reflect.ValueOf(options.MergeSessionOptions),
		"MergeTransactionOptions":            reflect.ValueOf(options.MergeTransactionOptions),
		"MergeUpdateOptions":                 reflect.ValueOf(options.MergeUpdateOptions),
		"MergeUploadOptions":                 reflect.ValueOf(options.MergeUploadOptions),
		"NonTailable":                        reflect.ValueOf(options.NonTailable),
		"Off":                                reflect.ValueOf(options.Off),
		"QueryTypeEquality":                  reflect.ValueOf(options.QueryTypeEquality),
		"Replace":                            reflect.ValueOf(options.Replace),
		"Required":                           reflect.ValueOf(options.Required),
		"RewrapManyDataKey":                  reflect.ValueOf(options.RewrapManyDataKey),
		"RunCmd":                             reflect.ValueOf(options.RunCmd),
		"SearchIndexes":                      reflect.ValueOf(options.SearchIndexes),
		"ServerAPI":                          reflect.ValueOf(options.ServerAPI),
		"ServerAPIVersion1":                  reflect.ValueOf(options.ServerAPIVersion1),
		"ServerMonitoringModeAuto":           reflect.ValueOf(constant.MakeFromLiteral("\"auto\"", token.STRING, 0)),
		"ServerMonitoringModePoll":           reflect.ValueOf(constant.MakeFromLiteral("\"poll\"", token.STRING, 0)),
		"ServerMonitoringModeStream":         reflect.ValueOf(constant.MakeFromLiteral("\"stream\"", token.STRING, 0)),
		"Session":                            reflect.ValueOf(options.Session),
		"Tailable":                           reflect.ValueOf(options.Tailable),
		"TailableAwait":                      reflect.ValueOf(options.TailableAwait),
		"TimeSeries":                         reflect.ValueOf(options.TimeSeries),
		"Transaction":                        reflect.ValueOf(options.Transaction),
		"Update":                             reflect.ValueOf(options.Update),
		"UpdateLookup":                       reflect.ValueOf(options.UpdateLookup),
		"WhenAvailable":                      reflect.ValueOf(options.WhenAvailable),

		// type definitions
		"AggregateOptions":              reflect.ValueOf((*options.AggregateOptions)(nil)),
		"ArrayFilters":                  reflect.ValueOf((*options.ArrayFilters)(nil)),
		"AutoEncryptionOptions":         reflect.ValueOf((*options.AutoEncryptionOptions)(nil)),
		"BSONOptions":                   reflect.ValueOf((*options.BSONOptions)(nil)),
		"BucketOptions":                 reflect.ValueOf((*options.BucketOptions)(nil)),
		"BulkWriteOptions":              reflect.ValueOf((*options.BulkWriteOptions)(nil)),
		"ChangeStreamOptions":           reflect.ValueOf((*options.ChangeStreamOptions)(nil)),
		"ClientEncryptionOptions":       reflect.ValueOf((*options.ClientEncryptionOptions)(nil)),
		"ClientOptions":                 reflect.ValueOf((*options.ClientOptions)(nil)),
		"Collation":                     reflect.ValueOf((*options.Collation)(nil)),
		"CollectionOptions":             reflect.ValueOf((*options.CollectionOptions)(nil)),
		"ContextDialer":                 reflect.ValueOf((*options.ContextDialer)(nil)),
		"CountOptions":                  reflect.ValueOf((*options.CountOptions)(nil)),
		"CreateCollectionOptions":       reflect.ValueOf((*options.CreateCollectionOptions)(nil)),
		"CreateIndexesOptions":          reflect.ValueOf((*options.CreateIndexesOptions)(nil)),
		"CreateSearchIndexesOptions":    reflect.ValueOf((*options.CreateSearchIndexesOptions)(nil)),
		"CreateViewOptions":             reflect.ValueOf((*options.CreateViewOptions)(nil)),
		"Credential":                    reflect.ValueOf((*options.Credential)(nil)),
		"CursorType":                    reflect.ValueOf((*options.CursorType)(nil)),
		"DataKeyOptions":                reflect.ValueOf((*options.DataKeyOptions)(nil)),
		"DatabaseOptions":               reflect.ValueOf((*options.DatabaseOptions)(nil)),
		"DefaultIndexOptions":           reflect.ValueOf((*options.DefaultIndexOptions)(nil)),
		"DeleteOptions":                 reflect.ValueOf((*options.DeleteOptions)(nil)),
		"DistinctOptions":               reflect.ValueOf((*options.DistinctOptions)(nil)),
		"DropIndexesOptions":            reflect.ValueOf((*options.DropIndexesOptions)(nil)),
		"DropSearchIndexOptions":        reflect.ValueOf((*options.DropSearchIndexOptions)(nil)),
		"EncryptOptions":                reflect.ValueOf((*options.EncryptOptions)(nil)),
		"EstimatedDocumentCountOptions": reflect.ValueOf((*options.EstimatedDocumentCountOptions)(nil)),
		"FindOneAndDeleteOptions":       reflect.ValueOf((*options.FindOneAndDeleteOptions)(nil)),
		"FindOneAndReplaceOptions":      reflect.ValueOf((*options.FindOneAndReplaceOptions)(nil)),
		"FindOneAndUpdateOptions":       reflect.ValueOf((*options.FindOneAndUpdateOptions)(nil)),
		"FindOneOptions":                reflect.ValueOf((*options.FindOneOptions)(nil)),
		"FindOptions":                   reflect.ValueOf((*options.FindOptions)(nil)),
		"FullDocument":                  reflect.ValueOf((*options.FullDocument)(nil)),
		"GridFSFindOptions":             reflect.ValueOf((*options.GridFSFindOptions)(nil)),
		"IndexOptions":                  reflect.ValueOf((*options.IndexOptions)(nil)),
		"InsertManyOptions":             reflect.ValueOf((*options.InsertManyOptions)(nil)),
		"InsertOneOptions":              reflect.ValueOf((*options.InsertOneOptions)(nil)),
		"ListCollectionsOptions":        reflect.ValueOf((*options.ListCollectionsOptions)(nil)),
		"ListDatabasesOptions":          reflect.ValueOf((*options.ListDatabasesOptions)(nil)),
		"ListIndexesOptions":            reflect.ValueOf((*options.ListIndexesOptions)(nil)),
		"ListSearchIndexesOptions":      reflect.ValueOf((*options.ListSearchIndexesOptions)(nil)),
		"LogComponent":                  reflect.ValueOf((*options.LogComponent)(nil)),
		"LogLevel":                      reflect.ValueOf((*options.LogLevel)(nil)),
		"LogSink":                       reflect.ValueOf((*options.LogSink)(nil)),
		"LoggerOptions":                 reflect.ValueOf((*options.LoggerOptions)(nil)),
		"MarshalError":                  reflect.ValueOf((*options.MarshalError)(nil)),
		"NameOptions":                   reflect.ValueOf((*options.NameOptions)(nil)),
		"RangeOptions":                  reflect.ValueOf((*options.RangeOptions)(nil)),
		"ReplaceOptions":                reflect.ValueOf((*options.ReplaceOptions)(nil)),
		"ReturnDocument":                reflect.ValueOf((*options.ReturnDocument)(nil)),
		"RewrapManyDataKeyOptions":      reflect.ValueOf((*options.RewrapManyDataKeyOptions)(nil)),
		"RunCmdOptions":                 reflect.ValueOf((*options.RunCmdOptions)(nil)),
		"SearchIndexesOptions":          reflect.ValueOf((*options.SearchIndexesOptions)(nil)),
		"ServerAPIOptions":              reflect.ValueOf((*options.ServerAPIOptions)(nil)),
		"ServerAPIVersion":              reflect.ValueOf((*options.ServerAPIVersion)(nil)),
		"SessionOptions":                reflect.ValueOf((*options.SessionOptions)(nil)),
		"TimeSeriesOptions":             reflect.ValueOf((*options.TimeSeriesOptions)(nil)),
		"TransactionOptions":            reflect.ValueOf((*options.TransactionOptions)(nil)),
		"UpdateOptions":                 reflect.ValueOf((*options.UpdateOptions)(nil)),
		"UpdateSearchIndexOptions":      reflect.ValueOf((*options.UpdateSearchIndexOptions)(nil)),
		"UploadOptions":                 reflect.ValueOf((*options.UploadOptions)(nil)),

		// interface wrapper definitions
		"_ContextDialer": reflect.ValueOf((*_go_mongodb_org_mongo_driver_mongo_options_ContextDialer)(nil)),
		"_LogSink":       reflect.ValueOf((*_go_mongodb_org_mongo_driver_mongo_options_LogSink)(nil)),
	}
}

// _go_mongodb_org_mongo_driver_mongo_options_ContextDialer is an interface wrapper for ContextDialer type
type _go_mongodb_org_mongo_driver_mongo_options_ContextDialer struct {
	IValue       interface{}
	WDialContext func(ctx context.Context, network string, address string) (net.Conn, error)
}

func (W _go_mongodb_org_mongo_driver_mongo_options_ContextDialer) DialContext(ctx context.Context, network string, address string) (net.Conn, error) {
	return W.WDialContext(ctx, network, address)
}

// _go_mongodb_org_mongo_driver_mongo_options_LogSink is an interface wrapper for LogSink type
type _go_mongodb_org_mongo_driver_mongo_options_LogSink struct {
	IValue interface{}
	WError func(err error, message string, keysAndValues ...interface{})
	WInfo  func(level int, message string, keysAndValues ...interface{})
}

func (W _go_mongodb_org_mongo_driver_mongo_options_LogSink) Error(err error, message string, keysAndValues ...interface{}) {
	W.WError(err, message, keysAndValues...)
}
func (W _go_mongodb_org_mongo_driver_mongo_options_LogSink) Info(level int, message string, keysAndValues ...interface{}) {
	W.WInfo(level, message, keysAndValues...)
}
