// Code generated by 'yaegi extract go.mongodb.org/mongo-driver/mongo'. DO NOT EDIT.

package symbols

import (
	"context"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"go.mongodb.org/mongo-driver/x/mongo/driver/session"
	"net"
	"reflect"
	"time"
)

func init() {
	Symbols["go.mongodb.org/mongo-driver/mongo/mongo"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BatchCursorFromCursor":       reflect.ValueOf(mongo.BatchCursorFromCursor),
		"ClientStream":                reflect.ValueOf(mongo.ClientStream),
		"CollectionStream":            reflect.ValueOf(mongo.CollectionStream),
		"Connect":                     reflect.ValueOf(mongo.Connect),
		"DatabaseStream":              reflect.ValueOf(mongo.DatabaseStream),
		"ErrClientDisconnected":       reflect.ValueOf(&mongo.ErrClientDisconnected).Elem(),
		"ErrEmptySlice":               reflect.ValueOf(&mongo.ErrEmptySlice).Elem(),
		"ErrInvalidIndexValue":        reflect.ValueOf(&mongo.ErrInvalidIndexValue).Elem(),
		"ErrMissingResumeToken":       reflect.ValueOf(&mongo.ErrMissingResumeToken).Elem(),
		"ErrMultipleIndexDrop":        reflect.ValueOf(&mongo.ErrMultipleIndexDrop).Elem(),
		"ErrNilCursor":                reflect.ValueOf(&mongo.ErrNilCursor).Elem(),
		"ErrNilDocument":              reflect.ValueOf(&mongo.ErrNilDocument).Elem(),
		"ErrNilValue":                 reflect.ValueOf(&mongo.ErrNilValue).Elem(),
		"ErrNoDocuments":              reflect.ValueOf(&mongo.ErrNoDocuments).Elem(),
		"ErrNonStringIndexName":       reflect.ValueOf(&mongo.ErrNonStringIndexName).Elem(),
		"ErrUnacknowledgedWrite":      reflect.ValueOf(&mongo.ErrUnacknowledgedWrite).Elem(),
		"ErrWrongClient":              reflect.ValueOf(&mongo.ErrWrongClient).Elem(),
		"IsDuplicateKeyError":         reflect.ValueOf(mongo.IsDuplicateKeyError),
		"IsNetworkError":              reflect.ValueOf(mongo.IsNetworkError),
		"IsTimeout":                   reflect.ValueOf(mongo.IsTimeout),
		"NewClient":                   reflect.ValueOf(mongo.NewClient),
		"NewClientEncryption":         reflect.ValueOf(mongo.NewClientEncryption),
		"NewCursorFromDocuments":      reflect.ValueOf(mongo.NewCursorFromDocuments),
		"NewDeleteManyModel":          reflect.ValueOf(mongo.NewDeleteManyModel),
		"NewDeleteOneModel":           reflect.ValueOf(mongo.NewDeleteOneModel),
		"NewIndexOptionsBuilder":      reflect.ValueOf(mongo.NewIndexOptionsBuilder),
		"NewInsertOneModel":           reflect.ValueOf(mongo.NewInsertOneModel),
		"NewReplaceOneModel":          reflect.ValueOf(mongo.NewReplaceOneModel),
		"NewSessionContext":           reflect.ValueOf(mongo.NewSessionContext),
		"NewSingleResultFromDocument": reflect.ValueOf(mongo.NewSingleResultFromDocument),
		"NewUpdateManyModel":          reflect.ValueOf(mongo.NewUpdateManyModel),
		"NewUpdateOneModel":           reflect.ValueOf(mongo.NewUpdateOneModel),
		"SessionFromContext":          reflect.ValueOf(mongo.SessionFromContext),
		"WithSession":                 reflect.ValueOf(mongo.WithSession),

		// type definitions
		"BSONAppender":             reflect.ValueOf((*mongo.BSONAppender)(nil)),
		"BSONAppenderFunc":         reflect.ValueOf((*mongo.BSONAppenderFunc)(nil)),
		"BulkWriteError":           reflect.ValueOf((*mongo.BulkWriteError)(nil)),
		"BulkWriteException":       reflect.ValueOf((*mongo.BulkWriteException)(nil)),
		"BulkWriteResult":          reflect.ValueOf((*mongo.BulkWriteResult)(nil)),
		"ChangeStream":             reflect.ValueOf((*mongo.ChangeStream)(nil)),
		"Client":                   reflect.ValueOf((*mongo.Client)(nil)),
		"ClientEncryption":         reflect.ValueOf((*mongo.ClientEncryption)(nil)),
		"Collection":               reflect.ValueOf((*mongo.Collection)(nil)),
		"CollectionSpecification":  reflect.ValueOf((*mongo.CollectionSpecification)(nil)),
		"CommandError":             reflect.ValueOf((*mongo.CommandError)(nil)),
		"Cursor":                   reflect.ValueOf((*mongo.Cursor)(nil)),
		"Database":                 reflect.ValueOf((*mongo.Database)(nil)),
		"DatabaseSpecification":    reflect.ValueOf((*mongo.DatabaseSpecification)(nil)),
		"DeleteManyModel":          reflect.ValueOf((*mongo.DeleteManyModel)(nil)),
		"DeleteOneModel":           reflect.ValueOf((*mongo.DeleteOneModel)(nil)),
		"DeleteResult":             reflect.ValueOf((*mongo.DeleteResult)(nil)),
		"Dialer":                   reflect.ValueOf((*mongo.Dialer)(nil)),
		"EncryptionKeyVaultError":  reflect.ValueOf((*mongo.EncryptionKeyVaultError)(nil)),
		"ErrMapForOrderedArgument": reflect.ValueOf((*mongo.ErrMapForOrderedArgument)(nil)),
		"IndexModel":               reflect.ValueOf((*mongo.IndexModel)(nil)),
		"IndexOptionsBuilder":      reflect.ValueOf((*mongo.IndexOptionsBuilder)(nil)),
		"IndexSpecification":       reflect.ValueOf((*mongo.IndexSpecification)(nil)),
		"IndexView":                reflect.ValueOf((*mongo.IndexView)(nil)),
		"InsertManyResult":         reflect.ValueOf((*mongo.InsertManyResult)(nil)),
		"InsertOneModel":           reflect.ValueOf((*mongo.InsertOneModel)(nil)),
		"InsertOneResult":          reflect.ValueOf((*mongo.InsertOneResult)(nil)),
		"LabeledError":             reflect.ValueOf((*mongo.LabeledError)(nil)),
		"ListDatabasesResult":      reflect.ValueOf((*mongo.ListDatabasesResult)(nil)),
		"MarshalError":             reflect.ValueOf((*mongo.MarshalError)(nil)),
		"MongocryptError":          reflect.ValueOf((*mongo.MongocryptError)(nil)),
		"MongocryptdError":         reflect.ValueOf((*mongo.MongocryptdError)(nil)),
		"Pipeline":                 reflect.ValueOf((*mongo.Pipeline)(nil)),
		"ReplaceOneModel":          reflect.ValueOf((*mongo.ReplaceOneModel)(nil)),
		"RewrapManyDataKeyResult":  reflect.ValueOf((*mongo.RewrapManyDataKeyResult)(nil)),
		"SearchIndexModel":         reflect.ValueOf((*mongo.SearchIndexModel)(nil)),
		"SearchIndexView":          reflect.ValueOf((*mongo.SearchIndexView)(nil)),
		"ServerError":              reflect.ValueOf((*mongo.ServerError)(nil)),
		"Session":                  reflect.ValueOf((*mongo.Session)(nil)),
		"SessionContext":           reflect.ValueOf((*mongo.SessionContext)(nil)),
		"SingleResult":             reflect.ValueOf((*mongo.SingleResult)(nil)),
		"StreamType":               reflect.ValueOf((*mongo.StreamType)(nil)),
		"UpdateManyModel":          reflect.ValueOf((*mongo.UpdateManyModel)(nil)),
		"UpdateOneModel":           reflect.ValueOf((*mongo.UpdateOneModel)(nil)),
		"UpdateResult":             reflect.ValueOf((*mongo.UpdateResult)(nil)),
		"WriteConcernError":        reflect.ValueOf((*mongo.WriteConcernError)(nil)),
		"WriteError":               reflect.ValueOf((*mongo.WriteError)(nil)),
		"WriteErrors":              reflect.ValueOf((*mongo.WriteErrors)(nil)),
		"WriteException":           reflect.ValueOf((*mongo.WriteException)(nil)),
		"WriteModel":               reflect.ValueOf((*mongo.WriteModel)(nil)),
		"XSession":                 reflect.ValueOf((*mongo.XSession)(nil)),

		// interface wrapper definitions
		"_BSONAppender":   reflect.ValueOf((*_go_mongodb_org_mongo_driver_mongo_BSONAppender)(nil)),
		"_Dialer":         reflect.ValueOf((*_go_mongodb_org_mongo_driver_mongo_Dialer)(nil)),
		"_LabeledError":   reflect.ValueOf((*_go_mongodb_org_mongo_driver_mongo_LabeledError)(nil)),
		"_ServerError":    reflect.ValueOf((*_go_mongodb_org_mongo_driver_mongo_ServerError)(nil)),
		"_Session":        reflect.ValueOf((*_go_mongodb_org_mongo_driver_mongo_Session)(nil)),
		"_SessionContext": reflect.ValueOf((*_go_mongodb_org_mongo_driver_mongo_SessionContext)(nil)),
		"_WriteModel":     reflect.ValueOf((*_go_mongodb_org_mongo_driver_mongo_WriteModel)(nil)),
		"_XSession":       reflect.ValueOf((*_go_mongodb_org_mongo_driver_mongo_XSession)(nil)),
	}
}

// _go_mongodb_org_mongo_driver_mongo_BSONAppender is an interface wrapper for BSONAppender type
type _go_mongodb_org_mongo_driver_mongo_BSONAppender struct {
	IValue      interface{}
	WAppendBSON func(a0 []byte, a1 interface{}) ([]byte, error)
}

func (W _go_mongodb_org_mongo_driver_mongo_BSONAppender) AppendBSON(a0 []byte, a1 interface{}) ([]byte, error) {
	return W.WAppendBSON(a0, a1)
}

// _go_mongodb_org_mongo_driver_mongo_Dialer is an interface wrapper for Dialer type
type _go_mongodb_org_mongo_driver_mongo_Dialer struct {
	IValue       interface{}
	WDialContext func(ctx context.Context, network string, address string) (net.Conn, error)
}

func (W _go_mongodb_org_mongo_driver_mongo_Dialer) DialContext(ctx context.Context, network string, address string) (net.Conn, error) {
	return W.WDialContext(ctx, network, address)
}

// _go_mongodb_org_mongo_driver_mongo_LabeledError is an interface wrapper for LabeledError type
type _go_mongodb_org_mongo_driver_mongo_LabeledError struct {
	IValue         interface{}
	WError         func() string
	WHasErrorLabel func(a0 string) bool
}

func (W _go_mongodb_org_mongo_driver_mongo_LabeledError) Error() string {
	return W.WError()
}
func (W _go_mongodb_org_mongo_driver_mongo_LabeledError) HasErrorLabel(a0 string) bool {
	return W.WHasErrorLabel(a0)
}

// _go_mongodb_org_mongo_driver_mongo_ServerError is an interface wrapper for ServerError type
type _go_mongodb_org_mongo_driver_mongo_ServerError struct {
	IValue                   interface{}
	WError                   func() string
	WHasErrorCode            func(a0 int) bool
	WHasErrorCodeWithMessage func(a0 int, a1 string) bool
	WHasErrorLabel           func(a0 string) bool
	WHasErrorMessage         func(a0 string) bool
}

func (W _go_mongodb_org_mongo_driver_mongo_ServerError) Error() string {
	return W.WError()
}
func (W _go_mongodb_org_mongo_driver_mongo_ServerError) HasErrorCode(a0 int) bool {
	return W.WHasErrorCode(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_ServerError) HasErrorCodeWithMessage(a0 int, a1 string) bool {
	return W.WHasErrorCodeWithMessage(a0, a1)
}
func (W _go_mongodb_org_mongo_driver_mongo_ServerError) HasErrorLabel(a0 string) bool {
	return W.WHasErrorLabel(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_ServerError) HasErrorMessage(a0 string) bool {
	return W.WHasErrorMessage(a0)
}

// _go_mongodb_org_mongo_driver_mongo_Session is an interface wrapper for Session type
type _go_mongodb_org_mongo_driver_mongo_Session struct {
	IValue                interface{}
	WAbortTransaction     func(a0 context.Context) error
	WAdvanceClusterTime   func(a0 bson.Raw) error
	WAdvanceOperationTime func(a0 *primitive.Timestamp) error
	WClient               func() *mongo.Client
	WClusterTime          func() bson.Raw
	WCommitTransaction    func(a0 context.Context) error
	WEndSession           func(a0 context.Context)
	WID                   func() bson.Raw
	WOperationTime        func() *primitive.Timestamp
	WStartTransaction     func(a0 ...*options.TransactionOptions) error
	WWithTransaction      func(ctx context.Context, fn func(ctx mongo.SessionContext) (interface{}, error), opts ...*options.TransactionOptions) (interface{}, error)
}

func (W _go_mongodb_org_mongo_driver_mongo_Session) AbortTransaction(a0 context.Context) error {
	return W.WAbortTransaction(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_Session) AdvanceClusterTime(a0 bson.Raw) error {
	return W.WAdvanceClusterTime(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_Session) AdvanceOperationTime(a0 *primitive.Timestamp) error {
	return W.WAdvanceOperationTime(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_Session) Client() *mongo.Client {
	return W.WClient()
}
func (W _go_mongodb_org_mongo_driver_mongo_Session) ClusterTime() bson.Raw {
	return W.WClusterTime()
}
func (W _go_mongodb_org_mongo_driver_mongo_Session) CommitTransaction(a0 context.Context) error {
	return W.WCommitTransaction(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_Session) EndSession(a0 context.Context) {
	W.WEndSession(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_Session) ID() bson.Raw {
	return W.WID()
}
func (W _go_mongodb_org_mongo_driver_mongo_Session) OperationTime() *primitive.Timestamp {
	return W.WOperationTime()
}
func (W _go_mongodb_org_mongo_driver_mongo_Session) StartTransaction(a0 ...*options.TransactionOptions) error {
	return W.WStartTransaction(a0...)
}
func (W _go_mongodb_org_mongo_driver_mongo_Session) WithTransaction(ctx context.Context, fn func(ctx mongo.SessionContext) (interface{}, error), opts ...*options.TransactionOptions) (interface{}, error) {
	return W.WWithTransaction(ctx, fn, opts...)
}

// _go_mongodb_org_mongo_driver_mongo_SessionContext is an interface wrapper for SessionContext type
type _go_mongodb_org_mongo_driver_mongo_SessionContext struct {
	IValue                interface{}
	WAbortTransaction     func(a0 context.Context) error
	WAdvanceClusterTime   func(a0 bson.Raw) error
	WAdvanceOperationTime func(a0 *primitive.Timestamp) error
	WClient               func() *mongo.Client
	WClusterTime          func() bson.Raw
	WCommitTransaction    func(a0 context.Context) error
	WDeadline             func() (deadline time.Time, ok bool)
	WDone                 func() <-chan struct{}
	WEndSession           func(a0 context.Context)
	WErr                  func() error
	WID                   func() bson.Raw
	WOperationTime        func() *primitive.Timestamp
	WStartTransaction     func(a0 ...*options.TransactionOptions) error
	WValue                func(key any) any
	WWithTransaction      func(ctx context.Context, fn func(ctx mongo.SessionContext) (interface{}, error), opts ...*options.TransactionOptions) (interface{}, error)
}

func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) AbortTransaction(a0 context.Context) error {
	return W.WAbortTransaction(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) AdvanceClusterTime(a0 bson.Raw) error {
	return W.WAdvanceClusterTime(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) AdvanceOperationTime(a0 *primitive.Timestamp) error {
	return W.WAdvanceOperationTime(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) Client() *mongo.Client {
	return W.WClient()
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) ClusterTime() bson.Raw {
	return W.WClusterTime()
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) CommitTransaction(a0 context.Context) error {
	return W.WCommitTransaction(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) Deadline() (deadline time.Time, ok bool) {
	return W.WDeadline()
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) Done() <-chan struct{} {
	return W.WDone()
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) EndSession(a0 context.Context) {
	W.WEndSession(a0)
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) Err() error {
	return W.WErr()
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) ID() bson.Raw {
	return W.WID()
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) OperationTime() *primitive.Timestamp {
	return W.WOperationTime()
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) StartTransaction(a0 ...*options.TransactionOptions) error {
	return W.WStartTransaction(a0...)
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) Value(key any) any {
	return W.WValue(key)
}
func (W _go_mongodb_org_mongo_driver_mongo_SessionContext) WithTransaction(ctx context.Context, fn func(ctx mongo.SessionContext) (interface{}, error), opts ...*options.TransactionOptions) (interface{}, error) {
	return W.WWithTransaction(ctx, fn, opts...)
}

// _go_mongodb_org_mongo_driver_mongo_WriteModel is an interface wrapper for WriteModel type
type _go_mongodb_org_mongo_driver_mongo_WriteModel struct {
	IValue interface{}
}

// _go_mongodb_org_mongo_driver_mongo_XSession is an interface wrapper for XSession type
type _go_mongodb_org_mongo_driver_mongo_XSession struct {
	IValue         interface{}
	WClientSession func() *session.Client
}

func (W _go_mongodb_org_mongo_driver_mongo_XSession) ClientSession() *session.Client {
	return W.WClientSession()
}
