// Code generated by 'yaegi extract go.mongodb.org/mongo-driver/bson'. DO NOT EDIT.

package symbols

import (
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/bsontype"
	"reflect"
)

func init() {
	Symbols["go.mongodb.org/mongo-driver/bson/bson"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultRegistry":                  reflect.ValueOf(&bson.DefaultRegistry).Elem(),
		"ErrDecodeToNil":                   reflect.ValueOf(&bson.ErrDecodeToNil).Elem(),
		"ErrNilContext":                    reflect.ValueOf(&bson.ErrNilContext).Elem(),
		"ErrNilReader":                     reflect.ValueOf(&bson.ErrNilReader).Elem(),
		"ErrNilRegistry":                   reflect.ValueOf(&bson.ErrNilRegistry).Elem(),
		"IndentExtJSON":                    reflect.ValueOf(bson.IndentExtJSON),
		"Marshal":                          reflect.ValueOf(bson.Marshal),
		"MarshalAppend":                    reflect.ValueOf(bson.MarshalAppend),
		"MarshalAppendWithContext":         reflect.ValueOf(bson.MarshalAppendWithContext),
		"MarshalAppendWithRegistry":        reflect.ValueOf(bson.MarshalAppendWithRegistry),
		"MarshalExtJSON":                   reflect.ValueOf(bson.MarshalExtJSON),
		"MarshalExtJSONAppend":             reflect.ValueOf(bson.MarshalExtJSONAppend),
		"MarshalExtJSONAppendWithContext":  reflect.ValueOf(bson.MarshalExtJSONAppendWithContext),
		"MarshalExtJSONAppendWithRegistry": reflect.ValueOf(bson.MarshalExtJSONAppendWithRegistry),
		"MarshalExtJSONIndent":             reflect.ValueOf(bson.MarshalExtJSONIndent),
		"MarshalExtJSONWithContext":        reflect.ValueOf(bson.MarshalExtJSONWithContext),
		"MarshalExtJSONWithRegistry":       reflect.ValueOf(bson.MarshalExtJSONWithRegistry),
		"MarshalValue":                     reflect.ValueOf(bson.MarshalValue),
		"MarshalValueAppend":               reflect.ValueOf(bson.MarshalValueAppend),
		"MarshalValueAppendWithContext":    reflect.ValueOf(bson.MarshalValueAppendWithContext),
		"MarshalValueAppendWithRegistry":   reflect.ValueOf(bson.MarshalValueAppendWithRegistry),
		"MarshalValueWithContext":          reflect.ValueOf(bson.MarshalValueWithContext),
		"MarshalValueWithRegistry":         reflect.ValueOf(bson.MarshalValueWithRegistry),
		"MarshalWithContext":               reflect.ValueOf(bson.MarshalWithContext),
		"MarshalWithRegistry":              reflect.ValueOf(bson.MarshalWithRegistry),
		"NewDecoder":                       reflect.ValueOf(bson.NewDecoder),
		"NewDecoderWithContext":            reflect.ValueOf(bson.NewDecoderWithContext),
		"NewEncoder":                       reflect.ValueOf(bson.NewEncoder),
		"NewEncoderWithContext":            reflect.ValueOf(bson.NewEncoderWithContext),
		"NewFromIOReader":                  reflect.ValueOf(bson.NewFromIOReader),
		"NewRegistry":                      reflect.ValueOf(bson.NewRegistry),
		"NewRegistryBuilder":               reflect.ValueOf(bson.NewRegistryBuilder),
		"ReadDocument":                     reflect.ValueOf(bson.ReadDocument),
		"TypeArray":                        reflect.ValueOf(bson.TypeArray),
		"TypeBinary":                       reflect.ValueOf(bson.TypeBinary),
		"TypeBinaryBinaryOld":              reflect.ValueOf(bson.TypeBinaryBinaryOld),
		"TypeBinaryColumn":                 reflect.ValueOf(bson.TypeBinaryColumn),
		"TypeBinaryEncrypted":              reflect.ValueOf(bson.TypeBinaryEncrypted),
		"TypeBinaryFunction":               reflect.ValueOf(bson.TypeBinaryFunction),
		"TypeBinaryGeneric":                reflect.ValueOf(bson.TypeBinaryGeneric),
		"TypeBinaryMD5":                    reflect.ValueOf(bson.TypeBinaryMD5),
		"TypeBinarySensitive":              reflect.ValueOf(bson.TypeBinarySensitive),
		"TypeBinaryUUID":                   reflect.ValueOf(bson.TypeBinaryUUID),
		"TypeBinaryUUIDOld":                reflect.ValueOf(bson.TypeBinaryUUIDOld),
		"TypeBinaryUserDefined":            reflect.ValueOf(bson.TypeBinaryUserDefined),
		"TypeBoolean":                      reflect.ValueOf(bson.TypeBoolean),
		"TypeCodeWithScope":                reflect.ValueOf(bson.TypeCodeWithScope),
		"TypeDBPointer":                    reflect.ValueOf(bson.TypeDBPointer),
		"TypeDateTime":                     reflect.ValueOf(bson.TypeDateTime),
		"TypeDecimal128":                   reflect.ValueOf(bson.TypeDecimal128),
		"TypeDouble":                       reflect.ValueOf(bson.TypeDouble),
		"TypeEmbeddedDocument":             reflect.ValueOf(bson.TypeEmbeddedDocument),
		"TypeInt32":                        reflect.ValueOf(bson.TypeInt32),
		"TypeInt64":                        reflect.ValueOf(bson.TypeInt64),
		"TypeJavaScript":                   reflect.ValueOf(bson.TypeJavaScript),
		"TypeMaxKey":                       reflect.ValueOf(bson.TypeMaxKey),
		"TypeMinKey":                       reflect.ValueOf(bson.TypeMinKey),
		"TypeNull":                         reflect.ValueOf(bson.TypeNull),
		"TypeObjectID":                     reflect.ValueOf(bson.TypeObjectID),
		"TypeRegex":                        reflect.ValueOf(bson.TypeRegex),
		"TypeString":                       reflect.ValueOf(bson.TypeString),
		"TypeSymbol":                       reflect.ValueOf(bson.TypeSymbol),
		"TypeTimestamp":                    reflect.ValueOf(bson.TypeTimestamp),
		"TypeUndefined":                    reflect.ValueOf(bson.TypeUndefined),
		"Unmarshal":                        reflect.ValueOf(bson.Unmarshal),
		"UnmarshalExtJSON":                 reflect.ValueOf(bson.UnmarshalExtJSON),
		"UnmarshalExtJSONWithContext":      reflect.ValueOf(bson.UnmarshalExtJSONWithContext),
		"UnmarshalExtJSONWithRegistry":     reflect.ValueOf(bson.UnmarshalExtJSONWithRegistry),
		"UnmarshalValue":                   reflect.ValueOf(bson.UnmarshalValue),
		"UnmarshalValueWithRegistry":       reflect.ValueOf(bson.UnmarshalValueWithRegistry),
		"UnmarshalWithContext":             reflect.ValueOf(bson.UnmarshalWithContext),
		"UnmarshalWithRegistry":            reflect.ValueOf(bson.UnmarshalWithRegistry),

		// type definitions
		"A":                reflect.ValueOf((*bson.A)(nil)),
		"D":                reflect.ValueOf((*bson.D)(nil)),
		"Decoder":          reflect.ValueOf((*bson.Decoder)(nil)),
		"E":                reflect.ValueOf((*bson.E)(nil)),
		"Encoder":          reflect.ValueOf((*bson.Encoder)(nil)),
		"M":                reflect.ValueOf((*bson.M)(nil)),
		"Marshaler":        reflect.ValueOf((*bson.Marshaler)(nil)),
		"PrimitiveCodecs":  reflect.ValueOf((*bson.PrimitiveCodecs)(nil)),
		"Raw":              reflect.ValueOf((*bson.Raw)(nil)),
		"RawElement":       reflect.ValueOf((*bson.RawElement)(nil)),
		"RawValue":         reflect.ValueOf((*bson.RawValue)(nil)),
		"Unmarshaler":      reflect.ValueOf((*bson.Unmarshaler)(nil)),
		"ValueMarshaler":   reflect.ValueOf((*bson.ValueMarshaler)(nil)),
		"ValueUnmarshaler": reflect.ValueOf((*bson.ValueUnmarshaler)(nil)),
		"Zeroer":           reflect.ValueOf((*bson.Zeroer)(nil)),

		// interface wrapper definitions
		"_Marshaler":        reflect.ValueOf((*_go_mongodb_org_mongo_driver_bson_Marshaler)(nil)),
		"_Unmarshaler":      reflect.ValueOf((*_go_mongodb_org_mongo_driver_bson_Unmarshaler)(nil)),
		"_ValueMarshaler":   reflect.ValueOf((*_go_mongodb_org_mongo_driver_bson_ValueMarshaler)(nil)),
		"_ValueUnmarshaler": reflect.ValueOf((*_go_mongodb_org_mongo_driver_bson_ValueUnmarshaler)(nil)),
		"_Zeroer":           reflect.ValueOf((*_go_mongodb_org_mongo_driver_bson_Zeroer)(nil)),
	}
}

// _go_mongodb_org_mongo_driver_bson_Marshaler is an interface wrapper for Marshaler type
type _go_mongodb_org_mongo_driver_bson_Marshaler struct {
	IValue       interface{}
	WMarshalBSON func() ([]byte, error)
}

func (W _go_mongodb_org_mongo_driver_bson_Marshaler) MarshalBSON() ([]byte, error) {
	return W.WMarshalBSON()
}

// _go_mongodb_org_mongo_driver_bson_Unmarshaler is an interface wrapper for Unmarshaler type
type _go_mongodb_org_mongo_driver_bson_Unmarshaler struct {
	IValue         interface{}
	WUnmarshalBSON func(a0 []byte) error
}

func (W _go_mongodb_org_mongo_driver_bson_Unmarshaler) UnmarshalBSON(a0 []byte) error {
	return W.WUnmarshalBSON(a0)
}

// _go_mongodb_org_mongo_driver_bson_ValueMarshaler is an interface wrapper for ValueMarshaler type
type _go_mongodb_org_mongo_driver_bson_ValueMarshaler struct {
	IValue            interface{}
	WMarshalBSONValue func() (bsontype.Type, []byte, error)
}

func (W _go_mongodb_org_mongo_driver_bson_ValueMarshaler) MarshalBSONValue() (bsontype.Type, []byte, error) {
	return W.WMarshalBSONValue()
}

// _go_mongodb_org_mongo_driver_bson_ValueUnmarshaler is an interface wrapper for ValueUnmarshaler type
type _go_mongodb_org_mongo_driver_bson_ValueUnmarshaler struct {
	IValue              interface{}
	WUnmarshalBSONValue func(a0 bsontype.Type, a1 []byte) error
}

func (W _go_mongodb_org_mongo_driver_bson_ValueUnmarshaler) UnmarshalBSONValue(a0 bsontype.Type, a1 []byte) error {
	return W.WUnmarshalBSONValue(a0, a1)
}

// _go_mongodb_org_mongo_driver_bson_Zeroer is an interface wrapper for Zeroer type
type _go_mongodb_org_mongo_driver_bson_Zeroer struct {
	IValue  interface{}
	WIsZero func() bool
}

func (W _go_mongodb_org_mongo_driver_bson_Zeroer) IsZero() bool {
	return W.WIsZero()
}
